# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62406819c03403b81af018918150200b89db8c976efd46efb90726b2c630c81524b354fd749a5414bcd5873e0aac52fe862b9bdf7812ec91db3842fc0d842adf

test:
  secret_key_base: d69f26a6527121f849eba116419ee0cc9f10a9af988f3b9b906f290959da2fcff9be6c6bd4927eda8a6d319bc65cb3a8f07b1ef1d64799717dccf2874bec2dd4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
